import { Sentence, DailyTask } from './types';

// Full list of 150 sentences for the "Daily" batch
export const DAILY_SENTENCES: Sentence[] = [
  // 1–20: Basic Daily Use
  { id: 1, english: "Hello.", spanish: "Hola.", category: "Basic" },
  { id: 2, english: "How are you?", spanish: "¿Cómo estás?", category: "Basic" },
  { id: 3, english: "I am fine.", spanish: "Estoy bien.", category: "Basic" },
  { id: 4, english: "Thank you very much.", spanish: "Muchas gracias.", category: "Basic" },
  { id: 5, english: "You are welcome.", spanish: "De nada.", category: "Basic" },
  { id: 6, english: "Good morning.", spanish: "Buenos días.", category: "Basic" },
  { id: 7, english: "Good afternoon.", spanish: "Buenas tardes.", category: "Basic" },
  { id: 8, english: "Good night.", spanish: "Buenas noches.", category: "Basic" },
  { id: 9, english: "See you later.", spanish: "Hasta luego.", category: "Basic" },
  { id: 10, english: "What is your name?", spanish: "¿Cómo te llamas?", category: "Basic" },
  { id: 11, english: "My name is John.", spanish: "Mi nombre es John.", category: "Basic" },
  { id: 12, english: "Nice to meet you.", spanish: "Mucho gusto.", category: "Basic" },
  { id: 13, english: "Please help me.", spanish: "Por favor ayúdame.", category: "Basic" },
  { id: 14, english: "I don’t understand.", spanish: "No entiendo.", category: "Basic" },
  { id: 15, english: "Can you repeat that?", spanish: "¿Puedes repetir eso?", category: "Basic" },
  { id: 16, english: "Speak more slowly, please.", spanish: "Habla más despacio, por favor.", category: "Basic" },
  { id: 17, english: "Excuse me.", spanish: "Disculpe.", category: "Basic" },
  { id: 18, english: "I am sorry.", spanish: "Lo siento.", category: "Basic" },
  { id: 19, english: "What time is it?", spanish: "¿Qué hora es?", category: "Basic" },
  { id: 20, english: "It is very late.", spanish: "Es muy tarde.", category: "Basic" },

  // 21–40: Travel & Food
  { id: 21, english: "Where is the bathroom?", spanish: "¿Dónde está el baño?", category: "Travel" },
  { id: 22, english: "I need a taxi.", spanish: "Necesito un taxi.", category: "Travel" },
  { id: 23, english: "How much does it cost?", spanish: "¿Cuánto cuesta?", category: "Travel" },
  { id: 24, english: "That is too expensive.", spanish: "Eso es demasiado caro.", category: "Travel" },
  { id: 25, english: "Do you accept credit cards?", spanish: "¿Aceptan tarjetas de crédito?", category: "Travel" },
  { id: 26, english: "I want this.", spanish: "Quiero esto.", category: "Travel" },
  { id: 27, english: "I would like water.", spanish: "Me gustaría agua.", category: "Food" },
  { id: 28, english: "The food is delicious.", spanish: "La comida está deliciosa.", category: "Food" },
  { id: 29, english: "I am hungry.", spanish: "Tengo hambre.", category: "Food" },
  { id: 30, english: "I am thirsty.", spanish: "Tengo sed.", category: "Food" },
  { id: 31, english: "The check, please.", spanish: "La cuenta, por favor.", category: "Food" },
  { id: 32, english: "This is my hotel.", spanish: "Este es mi hotel.", category: "Travel" },
  { id: 33, english: "I have a reservation.", spanish: "Tengo una reservación.", category: "Travel" },
  { id: 34, english: "I am lost.", spanish: "Estoy perdido.", category: "Travel" },
  { id: 35, english: "Can you help me find this address?", spanish: "¿Puedes ayudarme a encontrar esta dirección?", category: "Travel" },
  { id: 36, english: "What bus should I take?", spanish: "¿Qué autobús debo tomar?", category: "Travel" },
  { id: 37, english: "I need a doctor.", spanish: "Necesito un médico.", category: "Health" },
  { id: 38, english: "Is it far from here?", spanish: "¿Está lejos de aquí?", category: "Travel" },
  { id: 39, english: "Turn left.", spanish: "Gira a la izquierda.", category: "Travel" },
  { id: 40, english: "Turn right.", spanish: "Gira a la derecha.", category: "Travel" },

  // 41–60: Work, School & General Life
  { id: 41, english: "I work in an office.", spanish: "Trabajo en una oficina.", category: "Work" },
  { id: 42, english: "I am a student.", spanish: "Soy estudiante.", category: "School" },
  { id: 43, english: "I like my job.", spanish: "Me gusta mi trabajo.", category: "Work" },
  { id: 44, english: "I am very busy today.", spanish: "Estoy muy ocupado hoy.", category: "Work" },
  { id: 45, english: "I have a meeting at noon.", spanish: "Tengo una reunión al mediodía.", category: "Work" },
  { id: 46, english: "I need more time.", spanish: "Necesito más tiempo.", category: "Work" },
  { id: 47, english: "This is very important.", spanish: "Esto es muy importante.", category: "General" },
  { id: 48, english: "I agree with you.", spanish: "Estoy de acuerdo contigo.", category: "General" },
  { id: 49, english: "I disagree.", spanish: "No estoy de acuerdo.", category: "General" },
  { id: 50, english: "Let’s do it.", spanish: "Hagámoslo.", category: "General" },
  { id: 51, english: "What do you think?", spanish: "¿Qué piensas?", category: "General" },
  { id: 52, english: "I am learning Spanish.", spanish: "Estoy aprendiendo español.", category: "General" },
  { id: 53, english: "Practice makes perfect.", spanish: "La práctica hace al maestro.", category: "General" },
  { id: 54, english: "I made a mistake.", spanish: "Cometí un error.", category: "General" },
  { id: 55, english: "No problem.", spanish: "No hay problema.", category: "General" },
  { id: 56, english: "Everything is ready.", spanish: "Todo está listo.", category: "General" },
  { id: 57, english: "I need to study more.", spanish: "Necesito estudiar más.", category: "School" },
  { id: 58, english: "This is easy.", spanish: "Esto es fácil.", category: "General" },
  { id: 59, english: "This is difficult.", spanish: "Esto es difícil.", category: "General" },
  { id: 60, english: "I will try again.", spanish: "Lo intentaré de nuevo.", category: "General" },

  // 61-100: Emotions & Expressions
  { id: 61, english: "I am happy today.", spanish: "Estoy feliz hoy.", category: "Emotions" },
  { id: 62, english: "I am tired.", spanish: "Estoy cansado.", category: "Emotions" },
  { id: 63, english: "I feel sick.", spanish: "Me siento enfermo.", category: "Health" },
  { id: 64, english: "I am excited.", spanish: "Estoy emocionado.", category: "Emotions" },
  { id: 65, english: "I am worried.", spanish: "Estoy preocupado.", category: "Emotions" },
  { id: 66, english: "I am bored.", spanish: "Estoy aburrido.", category: "Emotions" },
  { id: 67, english: "I feel better now.", spanish: "Me siento mejor ahora.", category: "Emotions" },
  { id: 68, english: "I am nervous.", spanish: "Estoy nervioso.", category: "Emotions" },
  { id: 69, english: "I am proud of you.", spanish: "Estoy orgulloso de ti.", category: "Emotions" },
  { id: 70, english: "I miss you.", spanish: "Te extraño.", category: "Emotions" },
  { id: 71, english: "I need to rest.", spanish: "Necesito descansar.", category: "Health" },
  { id: 72, english: "I want to sleep.", spanish: "Quiero dormir.", category: "Health" },
  { id: 73, english: "I just woke up.", spanish: "Acabo de despertar.", category: "General" },
  { id: 74, english: "I am ready.", spanish: "Estoy listo.", category: "General" },
  { id: 75, english: "I am not ready yet.", spanish: "Aún no estoy listo.", category: "General" },
  { id: 76, english: "I changed my mind.", spanish: "Cambié de opinión.", category: "General" },
  { id: 77, english: "I forgot.", spanish: "Olvidé.", category: "General" },
  { id: 78, english: "I remember now.", spanish: "Lo recuerdo ahora.", category: "General" },
  { id: 79, english: "I believe you.", spanish: "Te creo.", category: "General" },
  { id: 80, english: "I don’t believe it.", spanish: "No lo creo.", category: "General" },
  { id: 81, english: "I am serious.", spanish: "Hablo en serio.", category: "General" },
  { id: 82, english: "I was joking.", spanish: "Estaba bromeando.", category: "General" },
  { id: 83, english: "I promise.", spanish: "Lo prometo.", category: "General" },
  { id: 84, english: "It depends.", spanish: "Depende.", category: "General" },
  { id: 85, english: "I don’t care.", spanish: "No me importa.", category: "General" },
  { id: 86, english: "I care about you.", spanish: "Me importas.", category: "Emotions" },
  { id: 87, english: "Be careful.", spanish: "Ten cuidado.", category: "General" },
  { id: 88, english: "Take your time.", spanish: "Tómate tu tiempo.", category: "General" },
  { id: 89, english: "Hurry up.", spanish: "Date prisa.", category: "General" },
  { id: 90, english: "Calm down.", spanish: "Cálmate.", category: "Emotions" },
  { id: 91, english: "Don’t worry.", spanish: "No te preocupes.", category: "Emotions" },
  { id: 92, english: "Trust me.", spanish: "Confía en mí.", category: "General" },
  { id: 93, english: "Leave me alone.", spanish: "Déjame solo.", category: "Emotions" },
  { id: 94, english: "Follow me.", spanish: "Sígueme.", category: "General" },
  { id: 95, english: "Wait for me.", spanish: "Espérame.", category: "General" },
  { id: 96, english: "Come with me.", spanish: "Ven conmigo.", category: "General" },
  { id: 97, english: "Help yourself.", spanish: "Sírvete.", category: "General" },
  { id: 98, english: "Make yourself at home.", spanish: "Ponte cómodo.", category: "Social" },
  { id: 99, english: "That makes sense.", spanish: "Eso tiene sentido.", category: "General" },
  { id: 100, english: "That doesn’t make sense.", spanish: "Eso no tiene sentido.", category: "General" },

  // 101–140: Family, Friends & Social Life
  { id: 101, english: "This is my family.", spanish: "Esta es mi familia.", category: "Family" },
  { id: 102, english: "I live with my parents.", spanish: "Vivo con mis padres.", category: "Family" },
  { id: 103, english: "I have two brothers.", spanish: "Tengo dos hermanos.", category: "Family" },
  { id: 104, english: "I have one sister.", spanish: "Tengo una hermana.", category: "Family" },
  { id: 105, english: "I am married.", spanish: "Estoy casado.", category: "Family" },
  { id: 106, english: "I am single.", spanish: "Soy soltero.", category: "Family" },
  { id: 107, english: "I have children.", spanish: "Tengo hijos.", category: "Family" },
  { id: 108, english: "My son is ten years old.", spanish: "Mi hijo tiene diez años.", category: "Family" },
  { id: 109, english: "My daughter is five years old.", spanish: "Mi hija tiene cinco años.", category: "Family" },
  { id: 110, english: "My best friend lives nearby.", spanish: "Mi mejor amigo vive cerca.", category: "Social" },
  { id: 111, english: "We grew up together.", spanish: "Crecimos juntos.", category: "Social" },
  { id: 112, english: "I trust my family.", spanish: "Confío en mi familia.", category: "Family" },
  { id: 113, english: "My parents support me.", spanish: "Mis padres me apoyan.", category: "Family" },
  { id: 114, english: "I visit my grandparents often.", spanish: "Visito a mis abuelos a menudo.", category: "Family" },
  { id: 115, english: "My cousin is coming tomorrow.", spanish: "Mi primo viene mañana.", category: "Family" },
  { id: 116, english: "I will call you later.", spanish: "Te llamaré más tarde.", category: "Social" },
  { id: 117, english: "Let’s stay in touch.", spanish: "Mantengámonos en contacto.", category: "Social" },
  { id: 118, english: "I made a new friend.", spanish: "Hice un nuevo amigo.", category: "Social" },
  { id: 119, english: "He is very kind.", spanish: "Él es muy amable.", category: "Social" },
  { id: 120, english: "She is very intelligent.", spanish: "Ella es muy inteligente.", category: "Social" },
  { id: 121, english: "They are very friendly.", spanish: "Ellos son muy amigables.", category: "Social" },
  { id: 122, english: "We get along well.", spanish: "Nos llevamos bien.", category: "Social" },
  { id: 123, english: "I had a great time.", spanish: "La pasé muy bien.", category: "Social" },
  { id: 124, english: "It was fun.", spanish: "Fue divertido.", category: "Social" },
  { id: 125, english: "The party was amazing.", spanish: "La fiesta fue increíble.", category: "Social" },
  { id: 126, english: "Thank you for coming.", spanish: "Gracias por venir.", category: "Social" },
  { id: 127, english: "Thanks for the invitation.", spanish: "Gracias por la invitación.", category: "Social" },
  { id: 128, english: "I enjoyed your company.", spanish: "Disfruté tu compañía.", category: "Social" },
  { id: 129, english: "See you tomorrow.", spanish: "Nos vemos mañana.", category: "Social" },
  { id: 130, english: "Have a nice day.", spanish: "Que tengas un buen día.", category: "Social" },
  { id: 131, english: "Have a good night.", spanish: "Que tengas buena noche.", category: "Social" },
  { id: 132, english: "Safe travels.", spanish: "Buen viaje.", category: "Travel" },
  { id: 133, english: "Take care.", spanish: "Cuídate.", category: "Social" },
  { id: 134, english: "Goodbye, my friend.", spanish: "Adiós, amigo mío.", category: "Social" },
  { id: 135, english: "I will miss you.", spanish: "Te extrañaré.", category: "Social" },
  { id: 136, english: "Keep in touch.", spanish: "Mantente en contacto.", category: "Social" },
  { id: 137, english: "I hope to see you again.", spanish: "Espero verte de nuevo.", category: "Social" },
  { id: 138, english: "It was nice meeting you.", spanish: "Fue un placer conocerte.", category: "Social" },
  { id: 139, english: "Let’s meet again soon.", spanish: "Reunámonos pronto otra vez.", category: "Social" },
  { id: 140, english: "We had a long conversation.", spanish: "Tuvimos una larga conversación.", category: "Social" },

  // 141–150: Work, Business & Money
  { id: 141, english: "I work full-time.", spanish: "Trabajo a tiempo completo.", category: "Work" },
  { id: 142, english: "I work part-time.", spanish: "Trabajo medio tiempo.", category: "Work" },
  { id: 143, english: "I am looking for a job.", spanish: "Busco trabajo.", category: "Work" },
  { id: 144, english: "I got a new job.", spanish: "Conseguí un nuevo trabajo.", category: "Work" },
  { id: 145, english: "I got promoted.", spanish: "Me ascendieron.", category: "Work" },
  { id: 146, english: "I was fired.", spanish: "Me despidieron.", category: "Work" },
  { id: 147, english: "I quit my job.", spanish: "Renuncié a mi trabajo.", category: "Work" },
  { id: 148, english: "My boss is strict.", spanish: "Mi jefe es estricto.", category: "Work" },
  { id: 149, english: "My coworker is helpful.", spanish: "Mi compañero de trabajo es servicial.", category: "Work" },
  { id: 150, english: "I work from home.", spanish: "Trabajo desde casa.", category: "Work" }
];

export const INITIAL_TASKS: DailyTask[] = [
  { id: 'task_1', title: 'Daily Warmup', description: 'Learn 5 new sentences', xpReward: 50, isCompleted: false, type: 'learning' },
  { id: 'task_2', title: 'Gamer', description: 'Play one round of Sentence Match', xpReward: 100, isCompleted: false, type: 'game' },
  { id: 'task_3', title: 'Listener', description: 'Listen to 10 audio clips', xpReward: 30, isCompleted: false, type: 'listening' },
];

export const XP_PER_SENTENCE = 10;
export const XP_PER_GAME_WIN = 50;
export const LEVEL_THRESHOLDS = [0, 100, 300, 600, 1000, 1500, 2500, 5000];